Feat--simple-navbar
TypeSafe-Travellers/trippins pull request #43
Opened 2023-01-12 19:16 UTC by ssarkar551

2023-01-12 19:16 UTC, ssarkar551 commented
added simple navbar
![image](https://user-images.githubusercontent.com/46297022/212160502-ee242fa4-ccff-445b-a6ba-42e0a38d8606.png)

2023-01-12 19:21 UTC, AyanavaKarmakar commented on src/components/Navbar.tsx
> +// type Props = {};
```suggestion
```

2023-01-12 19:22 UTC, AyanavaKarmakar commented on src/components/Navbar.tsx
> +import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
```suggestion
import * as NavigationMenu from "@radix-ui/react-navigation-menu";
```

2023-01-12 19:25 UTC, ssarkar551 commented on src/components/Navbar.tsx
> +import * as NavigationMenuPrimitive from "@radix-ui/react-navigation-menu";
done

2023-01-12 19:37 UTC, AyanavaKarmakar requested changes

2023-01-12 19:37 UTC, AyanavaKarmakar commented on src/components/Navbar.tsx
> +import React from "react";
```suggestion
```

Not required in React v18

2023-01-12 19:37 UTC, AyanavaKarmakar commented on src/components/Navbar.tsx
> +
```suggestion
```

2023-01-13 08:55 UTC, AyanavaKarmakar commented on src/components/Navbar.tsx
> +              Resources
```suggestion
              Profile
```

2023-01-13 17:23 UTC, AyanavaKarmakar approved these changes
LGTM

2023-01-14 12:16 UTC, merged