feat: add about page
TypeSafe-Travellers/trippins pull request #66
Opened 2023-01-15 19:00 UTC by ssarkar551

2023-01-15 19:05 UTC, ssarkar551 commented
Added About page
![image](https://user-images.githubusercontent.com/46297022/212561691-463360b5-29b3-429a-ac0c-31ebba2e102c.png)

2023-01-15 19:37 UTC, AyanavaKarmakar requested changes
Add stuff from https://github.com/TypeSafe-Travellers/App/blob/dev/README.md

Skip the "About" & "Get Started" sections tho

2023-01-15 20:05 UTC, AyanavaKarmakar requested changes

2023-01-15 20:05 UTC, AyanavaKarmakar commented on src/pages/about.tsx
> +          This is a website for people who want to travel the world, but do not
Welcome to our group trip-planning app! We are a team of travel enthusiasts who understand the challenges of planning a group trip. We created this app to make the process as easy and stress-free as possible.

Our app allows users to create a trip itinerary, share it with their group, and collaborate on details such as accommodations, transportation, and activities.

We believe that group trip planning should be fun and exciting, not overwhelming. That's why we've designed our app to be user-friendly and intuitive.

Thank you for choosing our group trip-planning app. Happy travels!

2023-01-15 20:05 UTC, AyanavaKarmakar commented on src/pages/about.tsx
> +          &copy; 2023 Typesafe Travellers
```suggestion
          &copy; {new Date().getFullYear()} Typesafe Travellers
```

2023-01-15 20:05 UTC, AyanavaKarmakar commented on src/pages/about.tsx
> +          Made with &hearts; using the T3 stack
```suggestion
          Made with &hearts; by TypeSafe Travellers using the T3 stack
```

2023-01-15 20:41 UTC, AyanavaKarmakar requested changes

2023-01-15 20:41 UTC, AyanavaKarmakar commented on src/pages/about.tsx
> +          should be fun and exciting, not overwhelming. That is why we have
```suggestion
          should be fun and exciting, not overwhelming. That&apos;s why we&apos;ve
```

2023-01-16 13:28 UTC, AyanavaKarmakar commented
Updated

![image](https://user-images.githubusercontent.com/89210438/212689331-626a8e3f-54b8-4e7e-9204-89e3be632f39.png)

2023-01-16 13:29 UTC, AyanavaKarmakar approved these changes

2023-01-16 14:15 UTC, Nishith-Savla commented on src/pages/about.tsx
> +            possible. Our app allows users to create a trip itinerary, share it
```suggestion
            possible. Our web app allows users to create a trip itinerary, share it
```

2023-01-16 14:15 UTC, Nishith-Savla commented on src/pages/about.tsx
> +            you for choosing our group trip-planning app. Happy travels!
What about this?

```suggestion
            you for choosing our group trip-planning app. Bon voyage!
```

2023-01-16 14:18 UTC, Nishith-Savla commented on src/pages/about.tsx
> +              &copy; {new Date().getFullYear()}{" "}
```suggestion
              {`& ${new Date().getFullYear()} `}
```

2023-01-16 14:45 UTC, Nishith-Savla approved these changes

2023-01-16 14:45 UTC, merged