feat: add active page
TypeSafe-Travellers/trippins pull request #86
Opened 2023-01-23 18:39 UTC by ssarkar551

2023-01-23 18:53 UTC, AyanavaKarmakar requested changes

2023-01-23 18:53 UTC, AyanavaKarmakar commented on src/components/Misc/Navbar.tsx
> +                  ? "dark:indigo-300 text-indigo-700"
```suggestion
                  ? "dark:text-indigo-200 text-indigo-700"
```

2023-01-23 18:53 UTC, AyanavaKarmakar commented on src/components/Misc/Navbar.tsx
> +  const router = useRouter();
```suggestion
  const { pathname } = useRouter();
```

2023-01-23 18:53 UTC, AyanavaKarmakar commented on src/components/Misc/Navbar.tsx
> +  const router = useRouter();
only grab the required prop, the entire router instance is not needed

2023-01-23 18:53 UTC, AyanavaKarmakar commented on src/components/Misc/Navbar.tsx
> +                  ? "dark:indigo-300 text-indigo-700"
fix for other routes too

2023-01-23 19:04 UTC, AyanavaKarmakar approved these changes

2023-01-24 16:04 UTC, Nishith-Savla approved these changes

2023-01-24 16:04 UTC, merged